server :
  port : 10001
  servlet :
    context-path : /

spring :
  datasource :
    driver-class-name : org.mariadb.jdbc.Driver
    username :          root
    password :          root
    url :               jdbc:mariadb://localhost:3306/security
  jpa :
    hibernate :
      ddl-auto : create-drop
